package com.MoreSupra.visao;

import ImagensTabela.JTableRenderer;
import com.MoreSupra.Controle.IModelosControle;
import com.MoreSupra.Controle.IVeiculosControle;
import com.MoreSupra.Controle.ModelosControle;
import com.MoreSupra.Controle.VeiculosControle;
import com.MoreSupra.enumeration.tipoDoVeiculo;
import com.MoreSupra.enumeration.situacao;
import com.MoreSupra.enumeration.tipoDeCombustivel;
import com.MoreSupra.modelos.Modelos;
import com.MoreSupra.modelos.Veiculos;
import com.MoreSupra.visao.utill.limitaCaracteres;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.File;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.Action;
import javax.swing.DefaultComboBoxModel;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.Timer;
import javax.swing.table.DefaultTableModel;

public class telaVeiculos extends javax.swing.JFrame {
    String combustivel;
    String tipoVeiculo;
    String situacion;

    
    IVeiculosControle veiculoscontrole = new VeiculosControle();
    IModelosControle modeloControle = new ModelosControle();
    
    public telaVeiculos() {
        initComponents();
        carregarComboBox();
        jTextField_placa.setDocument(new limitaCaracteres(7, limitaCaracteres.tipoEntrada.PLACA));
        jTextField_renavam.setDocument(new limitaCaracteres(11, limitaCaracteres.tipoEntrada.NUMEROINTEIRO));
        jTextField_precodeCompra.setDocument(new limitaCaracteres(7, limitaCaracteres.tipoEntrada.PRECO));
        jTextField_precoDeVenda.setDocument(new limitaCaracteres(7, limitaCaracteres.tipoEntrada.PRECO));
        jTextField_quilometragem.setDocument(new limitaCaracteres(7, limitaCaracteres.tipoEntrada.PRECO));
        setExtendedState(MAXIMIZED_BOTH);
        jTextField8_idVeiculos.setEnabled(false);
        
        combustivel = tipoDeCombustivel.GASOLINA + "";
        tipoVeiculo = tipoDoVeiculo.HATCH+"";
        situacion = situacao.DISPONIVEL+"";
        
        
        try {
            ArrayList <Modelos> combolista = modeloControle.listagemModelos();
            int lim = combolista.size();
            String modelos[] = new String[lim];

            for(int i = 0; i < combolista.size(); i++){
                modelos[i] = combolista.get(i).getDescricao();
                jComboBox1_Modelos.addItem(modelos[i]);
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
        
        
        try {
            imprimirDados(veiculoscontrole.listagemVeiculos());
        } catch (Exception ex) {
            Logger.getLogger(telaVeiculos.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        jDialog1.setSize(700, 490);
        jDialog1.setLocationRelativeTo(null);
        jDialog1.setTitle("cadastroincompleto");
        jDialog1.setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        jDialog1.setResizable(false);
        
        jDialog2_confirmacao.setSize(700, 490);
        jDialog2_confirmacao.setLocationRelativeTo(null);
        jDialog2_confirmacao.setTitle("cadastroincompleto");
        jDialog2_confirmacao.setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        jDialog2_confirmacao.setResizable(false);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialog1 = new javax.swing.JDialog();
        jButton2_Confimar3 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jDialog2_confirmacao = new javax.swing.JDialog();
        jLabel8 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jTextField8_idVeiculos = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        jButton4_voltar = new javax.swing.JButton();
        jLabel25 = new javax.swing.JLabel();
        jTextField_placa = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        jTextField_renavam = new javax.swing.JTextField();
        jTextField_precodeCompra = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jTextField_precoDeVenda = new javax.swing.JTextField();
        jLabel30 = new javax.swing.JLabel();
        jComboBox1_combustivel = new javax.swing.JComboBox<>();
        jLabel31 = new javax.swing.JLabel();
        jComboBox1_tipoDoVeiculo = new javax.swing.JComboBox<>();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jTextField_quilometragem = new javax.swing.JTextField();
        jComboBox1_situacao = new javax.swing.JComboBox<>();
        jLabel34 = new javax.swing.JLabel();
        jButton1_alterar = new javax.swing.JButton();
        jButton2_incluir = new javax.swing.JButton();
        jComboBox1_anoFabricacao = new javax.swing.JComboBox<>();
        jComboBox1_AnoModelo = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel35 = new javax.swing.JLabel();
        jComboBox1_Modelos = new javax.swing.JComboBox<>();
        jLabel9_ModeloImage = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        jDialog1.setUndecorated(true);
        jDialog1.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton2_Confimar3.setFont(new java.awt.Font("Serif", 3, 28)); // NOI18N
        jButton2_Confimar3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/MoreSupra/visao/icons/OKICON.png"))); // NOI18N
        jButton2_Confimar3.setText(" OK");
        jButton2_Confimar3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153), 4));
        jButton2_Confimar3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2_Confimar3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2_Confimar3ActionPerformed(evt);
            }
        });
        jDialog1.getContentPane().add(jButton2_Confimar3, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 400, 100, -1));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/MoreSupra/visao/icons/arrrrr.png"))); // NOI18N
        jDialog1.getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 10, -1, 130));

        jLabel22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/MoreSupra/visao/icons/INITIALDCADASTROINVALIDO.gif"))); // NOI18N
        jLabel22.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153), 3));
        jDialog1.getContentPane().add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 250, 360, 200));

        jLabel36.setFont(new java.awt.Font("Serif", 3, 30)); // NOI18N
        jLabel36.setForeground(new java.awt.Color(255, 255, 255));
        jLabel36.setText("CADASTRO NÃO REALIZADO!");
        jDialog1.getContentPane().add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 120, 500, 50));

        jLabel37.setFont(new java.awt.Font("Serif", 3, 22)); // NOI18N
        jLabel37.setForeground(new java.awt.Color(255, 255, 255));
        jLabel37.setText("VERIFIQUE INFORMAÇÕES INVÁLIDAS OU CAMPOS VAZIOS");
        jDialog1.getContentPane().add(jLabel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, 690, 50));

        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/MoreSupra/visao/icons/FADETELA.jpg"))); // NOI18N
        jLabel18.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153), 4));
        jDialog1.getContentPane().add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, 490));

        jDialog2_confirmacao.setUndecorated(true);
        jDialog2_confirmacao.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/MoreSupra/visao/icons/arrrrr.png"))); // NOI18N
        jDialog2_confirmacao.getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 10, -1, 140));

        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/MoreSupra/visao/icons/confirmGif.gif"))); // NOI18N
        jLabel19.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153), 3));
        jDialog2_confirmacao.getContentPane().add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 250, 220, 190));

        jLabel20.setFont(new java.awt.Font("Serif", 3, 22)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("E EXIBIDOS NA TABELA");
        jDialog2_confirmacao.getContentPane().add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 190, 270, 50));

        jLabel21.setFont(new java.awt.Font("Serif", 3, 30)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setText("CADASTRO REALIZADO COM SUCESSO!!");
        jDialog2_confirmacao.getContentPane().add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 110, 600, 50));

        jLabel23.setFont(new java.awt.Font("Serif", 3, 22)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(255, 255, 255));
        jLabel23.setText("DADOS FORAM CADASTRADOS ");
        jDialog2_confirmacao.getContentPane().add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 150, 340, 50));

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/MoreSupra/visao/icons/FADETELA.jpg"))); // NOI18N
        jLabel17.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153), 4));
        jDialog2_confirmacao.getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, 490));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/MoreSupra/visao/icons/arrrrr.png"))); // NOI18N
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 190, 130));

        jLabel11.setFont(new java.awt.Font("Serif", 3, 36)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("CADASTRO DE VEÍCULOS");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 20, 440, 40));

        jTextField8_idVeiculos.setFont(new java.awt.Font("Arial Black", 3, 14)); // NOI18N
        jTextField8_idVeiculos.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        getContentPane().add(jTextField8_idVeiculos, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 70, 70, 40));

        jLabel24.setFont(new java.awt.Font("Serif", 3, 30)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(255, 255, 255));
        jLabel24.setText("ID");
        getContentPane().add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 70, -1, 40));

        jButton4_voltar.setFont(new java.awt.Font("Serif", 3, 24)); // NOI18N
        jButton4_voltar.setForeground(new java.awt.Color(51, 0, 153));
        jButton4_voltar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/MoreSupra/visao/icons/voltar (1).png"))); // NOI18N
        jButton4_voltar.setText(" VOLTAR");
        jButton4_voltar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        jButton4_voltar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton4_voltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4_voltarActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4_voltar, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 630, 169, -1));

        jLabel25.setFont(new java.awt.Font("Serif", 3, 30)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(255, 255, 255));
        jLabel25.setText("COMBUSTÍVEL");
        getContentPane().add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 320, -1, 40));

        jTextField_placa.setFont(new java.awt.Font("Arial Black", 3, 14)); // NOI18N
        jTextField_placa.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        jTextField_placa.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField_placaKeyTyped(evt);
            }
        });
        getContentPane().add(jTextField_placa, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 70, 230, 40));

        jLabel26.setFont(new java.awt.Font("Serif", 3, 30)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(255, 255, 255));
        jLabel26.setText("RENAVAM");
        getContentPane().add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 70, -1, 40));

        jTextField_renavam.setFont(new java.awt.Font("Arial Black", 3, 14)); // NOI18N
        jTextField_renavam.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        jTextField_renavam.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextField_renavamMouseClicked(evt);
            }
        });
        getContentPane().add(jTextField_renavam, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 70, 250, 40));

        jTextField_precodeCompra.setFont(new java.awt.Font("Arial Black", 3, 14)); // NOI18N
        jTextField_precodeCompra.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        getContentPane().add(jTextField_precodeCompra, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 120, 230, 40));

        jLabel27.setFont(new java.awt.Font("Serif", 3, 30)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(255, 255, 255));
        jLabel27.setText("PREÇO DE COMPRA");
        getContentPane().add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 120, -1, 40));

        jLabel28.setFont(new java.awt.Font("Serif", 3, 30)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(255, 255, 255));
        jLabel28.setText("ANO FABRICAÇÃO");
        getContentPane().add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 220, -1, 40));

        jLabel29.setFont(new java.awt.Font("Serif", 3, 30)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(255, 255, 255));
        jLabel29.setText("PREÇO DE VENDA");
        getContentPane().add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 120, -1, 40));

        jTextField_precoDeVenda.setFont(new java.awt.Font("Arial Black", 3, 14)); // NOI18N
        jTextField_precoDeVenda.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        getContentPane().add(jTextField_precoDeVenda, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 120, 250, 40));

        jLabel30.setFont(new java.awt.Font("Serif", 3, 30)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(255, 255, 255));
        jLabel30.setText("ANO MODELO");
        getContentPane().add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 270, -1, 40));

        jComboBox1_combustivel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        jComboBox1_combustivel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1_combustivelActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox1_combustivel, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 320, 160, 40));

        jLabel31.setFont(new java.awt.Font("Serif", 3, 30)); // NOI18N
        jLabel31.setForeground(new java.awt.Color(255, 255, 255));
        jLabel31.setText("PLACA");
        getContentPane().add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 70, -1, 40));

        jComboBox1_tipoDoVeiculo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        jComboBox1_tipoDoVeiculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1_tipoDoVeiculoActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox1_tipoDoVeiculo, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 220, 170, 40));

        jLabel32.setFont(new java.awt.Font("Serif", 3, 30)); // NOI18N
        jLabel32.setForeground(new java.awt.Color(255, 255, 255));
        jLabel32.setText("MODELO");
        getContentPane().add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 170, -1, 40));

        jLabel33.setFont(new java.awt.Font("Serif", 3, 30)); // NOI18N
        jLabel33.setForeground(new java.awt.Color(255, 255, 255));
        jLabel33.setText("QUILOMETRAGEM");
        getContentPane().add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 170, -1, 40));

        jTextField_quilometragem.setFont(new java.awt.Font("Arial Black", 3, 14)); // NOI18N
        jTextField_quilometragem.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        getContentPane().add(jTextField_quilometragem, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 170, 230, 40));

        jComboBox1_situacao.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        jComboBox1_situacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1_situacaoActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox1_situacao, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 270, 170, 40));

        jLabel34.setFont(new java.awt.Font("Serif", 3, 30)); // NOI18N
        jLabel34.setForeground(new java.awt.Color(255, 255, 255));
        jLabel34.setText("SITUAÇÃO");
        getContentPane().add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 270, -1, 40));

        jButton1_alterar.setFont(new java.awt.Font("Serif", 3, 24)); // NOI18N
        jButton1_alterar.setForeground(new java.awt.Color(51, 0, 153));
        jButton1_alterar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/MoreSupra/visao/icons/alterarIcone.png"))); // NOI18N
        jButton1_alterar.setText("  ALTERAR");
        jButton1_alterar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        jButton1_alterar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1_alterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1_alterarActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1_alterar, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 410, 169, -1));

        jButton2_incluir.setFont(new java.awt.Font("Serif", 3, 24)); // NOI18N
        jButton2_incluir.setForeground(new java.awt.Color(51, 0, 153));
        jButton2_incluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/MoreSupra/visao/icons/incluirIcone.png"))); // NOI18N
        jButton2_incluir.setText("  INCLUIR");
        jButton2_incluir.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        jButton2_incluir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2_incluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2_incluirActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2_incluir, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 370, 169, -1));

        jComboBox1_anoFabricacao.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1990", "1991", "1992", "1993", "1994", "1995", "1996", "1997", "1998", "1999", "2000", "2001", "2002", "2003", "2004", "2005", "2006", "2007", "2008", "2009", "2010", "2011", "2012" }));
        jComboBox1_anoFabricacao.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        jComboBox1_anoFabricacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1_anoFabricacaoActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox1_anoFabricacao, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 220, 160, 40));

        jComboBox1_AnoModelo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1990", "1991", "1992", "1993", "1994", "1995", "1996", "1997", "1998", "1999", "2000", "2001", "2002", "2003", "2004", "2005", "2006", "2007", "2008", "2009", "2010", "2011", "2012" }));
        jComboBox1_AnoModelo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        jComboBox1_AnoModelo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1_AnoModeloActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox1_AnoModelo, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 270, 160, 40));

        jTable1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        jTable1.setFont(new java.awt.Font("Serif", 3, 14)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "PLACA", "RENAVAM", "COMPRA", "VENDA", "ANO FA", "ANO MO", "KMS", "COMBUSTÍVEL", "TIPO", "SITUAÇÃO", "MODELO", "", ""
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.setRowHeight(60);
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setPreferredWidth(40);
            jTable1.getColumnModel().getColumn(1).setPreferredWidth(100);
            jTable1.getColumnModel().getColumn(2).setPreferredWidth(110);
            jTable1.getColumnModel().getColumn(3).setPreferredWidth(90);
            jTable1.getColumnModel().getColumn(4).setPreferredWidth(90);
            jTable1.getColumnModel().getColumn(7).setPreferredWidth(80);
            jTable1.getColumnModel().getColumn(8).setPreferredWidth(110);
            jTable1.getColumnModel().getColumn(10).setPreferredWidth(130);
            jTable1.getColumnModel().getColumn(11).setPreferredWidth(100);
            jTable1.getColumnModel().getColumn(12).setPreferredWidth(0);
            jTable1.getColumnModel().getColumn(13).setPreferredWidth(100);
        }

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 370, 930, 300));

        jLabel35.setFont(new java.awt.Font("Serif", 3, 30)); // NOI18N
        jLabel35.setForeground(new java.awt.Color(255, 255, 255));
        jLabel35.setText("TIPO DO VEÍCULO");
        getContentPane().add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 220, -1, 40));

        jComboBox1_Modelos.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        jComboBox1_Modelos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1_ModelosActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox1_Modelos, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 170, 170, 40));

        jLabel9_ModeloImage.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        getContentPane().add(jLabel9_ModeloImage, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 220, 210, 140));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/MoreSupra/visao/icons/FADETELA.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1800, 900));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton4_voltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4_voltarActionPerformed
        // TODO add your handling code here:
        TelaPrincipal princ = new TelaPrincipal();
        princ.setVisible(true);
        this.dispose();

    }//GEN-LAST:event_jButton4_voltarActionPerformed

    private void jComboBox1_combustivelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1_combustivelActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_jComboBox1_combustivelActionPerformed

    private void jComboBox1_tipoDoVeiculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1_tipoDoVeiculoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1_tipoDoVeiculoActionPerformed

    private void jComboBox1_situacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1_situacaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1_situacaoActionPerformed

    private void jButton1_alterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1_alterarActionPerformed
        // TODO add your handling code here:
        try {

        } catch (Exception erro) {
            JOptionPane.showMessageDialog(this, erro.getMessage());
        }
    }//GEN-LAST:event_jButton1_alterarActionPerformed

    public void imprimirDados(ArrayList<Veiculos> listaDeVeiculos){
        try {
            DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
            JTableRenderer JtableRenderer = new JTableRenderer();  
            jTable1.getColumnModel().getColumn(13).setCellRenderer(JtableRenderer);

            //Limpa a tabela 
            model.setNumRows(0);
            Iterator<Veiculos> lista = listaDeVeiculos.iterator();
            while(lista.hasNext()){
                String[] saida= new String[13];
                Veiculos aux = lista.next();
                saida[0]= aux.getId()+"";
                saida[1]= aux.getPlaca();
                saida[2] = aux.getRenavem()+"";
                saida[3] = aux.getPrecoDeVenda()+"";
                saida[4] = aux.getPrecoDeCompra()+"";
                saida[5] = aux.getAnoFabricacao();
                saida[6] = aux.getAnoModelo();
                saida[7] = aux.getQuilometragem()+"";
                saida[8] = aux.getTipoDeCombustivel().toString();
                saida[9] = aux.getTipoDoVeiculo().toString();
                saida[10] = aux.getSituacao().toString();
                saida[11] = modeloControle.buscar(aux.getModelo().getId()).getDescricao();
                saida[12] = modeloControle.buscar(aux.getModelo().getId()).getUrl();

                
                //Incluir nova linha na Tabela,saida[0]
                
                Object[]dados = {saida[0],saida[1],saida[2],saida[3], saida[4], saida[5], saida[6], saida[7], saida[8], saida[9],
                saida[10],saida[11], saida[12]};
                model.addRow(dados);
            }
        } catch(Exception erro){
            JOptionPane.showMessageDialog(this, erro.getMessage());
      }
    
    }
    
    
    private void jButton2_incluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2_incluirActionPerformed
        // TODO add your handling code here:
        try {
            File arquivo = new File("./src/com/MoreSupra/arquivoDisco/Veiculos.txt");
            arquivo.createNewFile();
            
            if (jComboBox1_combustivel.getSelectedIndex() == 0) {
                combustivel = tipoDeCombustivel.GASOLINA + "";                
            } else if(jComboBox1_combustivel.getSelectedIndex() == 1){                      
                combustivel = tipoDeCombustivel.DIESEL+"";     
            }else if(jComboBox1_combustivel.getSelectedIndex() == 2){
                combustivel = tipoDeCombustivel.FLEX+"";
            }else if (jComboBox1_combustivel.getSelectedIndex() == 3){
                combustivel = tipoDeCombustivel.ELETRICO+"";
            }else if (jComboBox1_combustivel.getSelectedIndex() == 4){
                combustivel = tipoDeCombustivel.GNV+"";
            }
            
            if(jComboBox1_situacao.getSelectedIndex() == 0){
                situacion = situacao.LOCADO+"";
            }else if(jComboBox1_situacao.getSelectedIndex() == 1){
                situacion = situacao.DISPONIVEL+"";
            }else if(jComboBox1_situacao.getSelectedIndex() == 2){
                situacion = situacao.MANUTENCAO+"";
            }else if(jComboBox1_situacao.getSelectedIndex() == 3){
                situacion = situacao.VENDIDO+"";
            }
            
            if(jComboBox1_tipoDoVeiculo.getSelectedIndex() == 0){
                tipoVeiculo = tipoDoVeiculo.HATCH+"";
            }else if (jComboBox1_tipoDoVeiculo.getSelectedIndex() == 1){
                tipoVeiculo = tipoDoVeiculo.SEDAN+"";
            }else if(jComboBox1_tipoDoVeiculo.getSelectedIndex() == 2){
                tipoVeiculo = tipoDoVeiculo.SUV+"";
            }else if(jComboBox1_tipoDoVeiculo.getSelectedIndex() == 3){
                tipoVeiculo = tipoDoVeiculo.PICKUP+"";
            }

            if(!jTextField_placa.getText().isEmpty() && !jTextField_renavam.getText().isEmpty() && !jTextField_precodeCompra.getText().isEmpty() &&
                    !jTextField_precoDeVenda.getText().isEmpty() && !jTextField_quilometragem.getText().isEmpty()){   
            int macc = 0;
            Veiculos veiculos = new Veiculos(0, jTextField_placa.getText(), Long.parseLong(jTextField_renavam.getText()), 
                    Float.parseFloat(jTextField_precodeCompra.getText()), 
                    Float.parseFloat(jTextField_precoDeVenda.getText()), 
                    jComboBox1_anoFabricacao.getSelectedItem().toString(), 
                    jComboBox1_AnoModelo.getSelectedItem().toString(), 
                    Long.parseLong(jTextField_quilometragem.getText()),
                    tipoDeCombustivel.valueOf(combustivel),
                    tipoDoVeiculo.valueOf(tipoVeiculo),
                    situacao.valueOf(situacion), modeloControle.buscar(macc));
                         
            ArrayList<Modelos> lista = modeloControle.listagemModelos();
            for(int i = 0; i < lista.size(); i++){
                if(jComboBox1_Modelos.getSelectedItem().equals(lista.get(i).getDescricao())){
                    veiculos.setModelo(lista.get(i)); 
                }
            }
            
            veiculoscontrole.incluir(veiculos);
            imprimirDados(veiculoscontrole.listagemVeiculos());
            jTextField_placa.setText("");
            jTextField_precoDeVenda.setText("");
            jTextField_precodeCompra.setText("");
            jTextField_quilometragem.setText("");
            jTextField_renavam.setText("");
            
            Timer timer = new Timer(4200, new ActionListener() {
                    public void actionPerformed(ActionEvent e) {
                    jDialog2_confirmacao.setVisible(false);
                    jDialog2_confirmacao.dispose();
                }
             });
                 timer.setRepeats(false);
                 timer.start();
                 jDialog2_confirmacao.setVisible(true);
            }else{
                jDialog1.setVisible(true);
            }
        } catch (Exception erro) {
            JOptionPane.showMessageDialog(this, erro.getMessage());
        }
    }//GEN-LAST:event_jButton2_incluirActionPerformed

    private void jComboBox1_anoFabricacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1_anoFabricacaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1_anoFabricacaoActionPerformed

    private void jComboBox1_AnoModeloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1_AnoModeloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1_AnoModeloActionPerformed

    private void jTextField_renavamMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField_renavamMouseClicked
        
        
    }//GEN-LAST:event_jTextField_renavamMouseClicked

    private void jTextField_placaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_placaKeyTyped
        char c=evt.getKeyChar();

        if(Character.isLowerCase(c)){
            evt.setKeyChar(Character.toUpperCase(c));
        }
    }//GEN-LAST:event_jTextField_placaKeyTyped

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
            
            jTextField8_idVeiculos.setText(jTable1.getValueAt(jTable1.getSelectedRow(), 0).toString());
            jTextField_placa.setText(jTable1.getValueAt(jTable1.getSelectedRow(), 1).toString());
            jTextField_renavam.setText(jTable1.getValueAt(jTable1.getSelectedRow(), 2).toString());
            jTextField_precoDeVenda.setText(jTable1.getValueAt(jTable1.getSelectedRow(), 3).toString());
            jTextField_precodeCompra.setText(jTable1.getValueAt(jTable1.getSelectedRow(), 4).toString());
            jComboBox1_anoFabricacao.setSelectedItem(jTable1.getValueAt(jTable1.getSelectedRow(), 5).toString());
            jComboBox1_AnoModelo.setSelectedItem(jTable1.getValueAt(jTable1.getSelectedRow(), 6).toString());
            jTextField_quilometragem.setText(jTable1.getValueAt(jTable1.getSelectedRow(), 7).toString());
            jComboBox1_combustivel.setSelectedItem(jTable1.getValueAt(jTable1.getSelectedRow(), 10).toString());
            jComboBox1_tipoDoVeiculo.setSelectedItem(jTable1.getValueAt(jTable1.getSelectedRow(), 9).toString());
            jComboBox1_situacao.setSelectedItem(jTable1.getValueAt(jTable1.getSelectedRow(), 10).toString());
            jComboBox1_Modelos.setSelectedItem(jTable1.getValueAt(jTable1.getSelectedRow(), 11).toString());
            
            Object pog = jTable1.getValueAt(jTable1.getSelectedRow(), 12);
            ImageIcon marca = new ImageIcon((String) pog);
            marca.setImage(marca.getImage().getScaledInstance(jLabel9_ModeloImage.getWidth(), 
            jLabel9_ModeloImage.getHeight(), 1));
            jLabel9_ModeloImage.setIcon(marca);
    }//GEN-LAST:event_jTable1MouseClicked

    private void jComboBox1_ModelosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1_ModelosActionPerformed
        try{
        int macc = 0;
            Veiculos veiculos = new Veiculos(0, jTextField_placa.getText(), Long.parseLong(jTextField_renavam.getText()), 
                    Float.parseFloat(jTextField_precodeCompra.getText()), 
                    Float.parseFloat(jTextField_precoDeVenda.getText()), 
                    jComboBox1_anoFabricacao.getSelectedItem().toString(), 
                    jComboBox1_AnoModelo.getSelectedItem().toString(), 
                    Long.parseLong(jTextField_quilometragem.getText()),
                    tipoDeCombustivel.valueOf(combustivel),
                    tipoDoVeiculo.valueOf(tipoVeiculo),
                    situacao.valueOf(situacion), modeloControle.buscar(macc));
           
            ArrayList<Modelos> lista = modeloControle.listagemModelos();
            for(int i = 0; i < lista.size(); i++){
                if(jComboBox1_Modelos.getSelectedItem().equals(lista.get(i).getDescricao())){
                    veiculos.setModelo(lista.get(i));
                    ImageIcon marca = new ImageIcon(lista.get(i).getUrl());
                marca.setImage(marca.getImage().getScaledInstance(jLabel9_ModeloImage.getWidth(), jLabel9_ModeloImage.getHeight(), 1));
                jLabel9_ModeloImage.setIcon(marca);
            }
        }
        }catch (Exception erro) {
                
        }
    }//GEN-LAST:event_jComboBox1_ModelosActionPerformed

    private void jButton2_Confimar3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2_Confimar3ActionPerformed
        jDialog1.dispose();
    }//GEN-LAST:event_jButton2_Confimar3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(telaVeiculos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(telaVeiculos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(telaVeiculos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(telaVeiculos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new telaVeiculos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1_alterar;
    private javax.swing.JButton jButton2_Confimar3;
    private javax.swing.JButton jButton2_incluir;
    private javax.swing.JButton jButton4_voltar;
    private javax.swing.JComboBox<String> jComboBox1_AnoModelo;
    private javax.swing.JComboBox<String> jComboBox1_Modelos;
    private javax.swing.JComboBox<String> jComboBox1_anoFabricacao;
    private javax.swing.JComboBox<tipoDeCombustivel> jComboBox1_combustivel;
    private javax.swing.JComboBox<situacao> jComboBox1_situacao;
    private javax.swing.JComboBox<tipoDoVeiculo> jComboBox1_tipoDoVeiculo;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JDialog jDialog2_confirmacao;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9_ModeloImage;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField8_idVeiculos;
    private javax.swing.JTextField jTextField_placa;
    private javax.swing.JTextField jTextField_precoDeVenda;
    private javax.swing.JTextField jTextField_precodeCompra;
    private javax.swing.JTextField jTextField_quilometragem;
    private javax.swing.JTextField jTextField_renavam;
    // End of variables declaration//GEN-END:variables

    private void carregarComboBox() {
        jComboBox1_situacao.setModel(new DefaultComboBoxModel<>(situacao.values()));
        jComboBox1_tipoDoVeiculo.setModel(new DefaultComboBoxModel<>(tipoDoVeiculo.values()));
        jComboBox1_combustivel.setModel(new DefaultComboBoxModel<>(tipoDeCombustivel.values()));
    }
}
