/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.MoreSupra.visao;

import java.io.File;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author Aluno
 */
public class TelaCliente extends javax.swing.JFrame {

    /**
     * Creates new form TelaCliente
     */
    public TelaCliente() {
        initComponents();
        setExtendedState(MAXIMIZED_BOTH);
        jTextField8_idJuridica.setEnabled(false);
        jTextField8_IDFisica.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFrame1 = new javax.swing.JFrame();
        jPanel3 = new javax.swing.JPanel();
        jButton4_voltar1 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jTextField1_identidade = new javax.swing.JTextField();
        jTextField2_nomeFisica = new javax.swing.JTextField();
        jTextField3_enderecoFisica = new javax.swing.JTextField();
        jTextField4_cpf = new javax.swing.JTextField();
        jTextField5_telefoneFisica = new javax.swing.JTextField();
        jTextField6_emailFIsica = new javax.swing.JTextField();
        jButton3_buscar = new javax.swing.JButton();
        jButton2_incluir = new javax.swing.JButton();
        jButton1_alterar = new javax.swing.JButton();
        jLabel22_FotoFisica = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jTextField8_IDFisica = new javax.swing.JTextField();
        jLabel28 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jFrame2 = new javax.swing.JFrame();
        jPanel4 = new javax.swing.JPanel();
        jButton4_voltar2 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jTextField8_enderecoJuridica = new javax.swing.JTextField();
        jTextField9_emailJuri = new javax.swing.JTextField();
        jTextField10_telefoneJuri = new javax.swing.JTextField();
        jTextField11_cnpj = new javax.swing.JTextField();
        jTextField12_nomeJuridica = new javax.swing.JTextField();
        jLabel22_FotoFisica1 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jButton1_alterar1 = new javax.swing.JButton();
        jButton2_incluir1 = new javax.swing.JButton();
        jButton3_buscar1 = new javax.swing.JButton();
        jTextField8_idJuridica = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton4_voltar = new javax.swing.JButton();
        jButton1_pessoaFisica = new javax.swing.JButton();
        jButton2_pessoaJuridica = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        jFrame1.setTitle("pessoaFisica");

        jPanel3.setPreferredSize(new java.awt.Dimension(1460, 710));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton4_voltar1.setFont(new java.awt.Font("Serif", 3, 24)); // NOI18N
        jButton4_voltar1.setForeground(new java.awt.Color(51, 0, 153));
        jButton4_voltar1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Aluno\\Downloads\\voltar (1).png")); // NOI18N
        jButton4_voltar1.setText(" VOLTAR");
        jButton4_voltar1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        jButton4_voltar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4_voltar1ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton4_voltar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1080, 610, 169, -1));

        jLabel8.setIcon(new javax.swing.ImageIcon("C:\\Users\\Aluno\\Downloads\\arrrrr.png")); // NOI18N
        jPanel3.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 190, 130));

        jLabel10.setFont(new java.awt.Font("Serif", 3, 30)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("ENDEREÇO");
        jPanel3.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 420, 170, 40));

        jLabel13.setFont(new java.awt.Font("Serif", 3, 36)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("CADASTRO PESSOA FÍSICA");
        jPanel3.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 40, 470, 40));

        jLabel14.setFont(new java.awt.Font("Serif", 3, 30)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("NOME");
        jPanel3.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 170, 100, 40));

        jLabel15.setFont(new java.awt.Font("Serif", 3, 30)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("IDENTIDADE");
        jPanel3.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 270, 190, 40));

        jLabel16.setFont(new java.awt.Font("Serif", 3, 30)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("CPF");
        jPanel3.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 220, 70, 40));

        jLabel17.setFont(new java.awt.Font("Serif", 3, 30)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("EMAIL");
        jPanel3.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 370, 170, 40));

        jLabel18.setFont(new java.awt.Font("Serif", 3, 30)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("TELEFONE");
        jPanel3.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 320, 170, 40));

        jTextField1_identidade.setFont(new java.awt.Font("Arial", 3, 14)); // NOI18N
        jPanel3.add(jTextField1_identidade, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 270, 270, 40));

        jTextField2_nomeFisica.setFont(new java.awt.Font("Arial", 3, 14)); // NOI18N
        jPanel3.add(jTextField2_nomeFisica, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 170, 480, 40));

        jTextField3_enderecoFisica.setFont(new java.awt.Font("Arial", 3, 14)); // NOI18N
        jPanel3.add(jTextField3_enderecoFisica, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 420, 400, 40));

        jTextField4_cpf.setFont(new java.awt.Font("Arial", 3, 14)); // NOI18N
        jPanel3.add(jTextField4_cpf, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 220, 270, 40));

        jTextField5_telefoneFisica.setFont(new java.awt.Font("Arial", 3, 14)); // NOI18N
        jPanel3.add(jTextField5_telefoneFisica, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 320, 300, 40));

        jTextField6_emailFIsica.setFont(new java.awt.Font("Arial", 3, 14)); // NOI18N
        jPanel3.add(jTextField6_emailFIsica, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 370, 480, 40));

        jButton3_buscar.setFont(new java.awt.Font("Serif", 3, 24)); // NOI18N
        jButton3_buscar.setForeground(new java.awt.Color(51, 0, 153));
        jButton3_buscar.setIcon(new javax.swing.ImageIcon("C:\\Users\\Aluno\\Downloads\\lupa4.0 (1).png")); // NOI18N
        jButton3_buscar.setText("  BUSCAR");
        jButton3_buscar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        jButton3_buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3_buscarActionPerformed(evt);
            }
        });
        jPanel3.add(jButton3_buscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(1070, 200, 169, -1));

        jButton2_incluir.setFont(new java.awt.Font("Serif", 3, 24)); // NOI18N
        jButton2_incluir.setForeground(new java.awt.Color(51, 0, 153));
        jButton2_incluir.setIcon(new javax.swing.ImageIcon("C:\\Users\\Aluno\\Downloads\\incluirIcone (1).png")); // NOI18N
        jButton2_incluir.setText("  INCLUIR");
        jButton2_incluir.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        jButton2_incluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2_incluirActionPerformed(evt);
            }
        });
        jPanel3.add(jButton2_incluir, new org.netbeans.lib.awtextra.AbsoluteConstraints(1070, 240, 169, -1));

        jButton1_alterar.setFont(new java.awt.Font("Serif", 3, 24)); // NOI18N
        jButton1_alterar.setForeground(new java.awt.Color(51, 0, 153));
        jButton1_alterar.setIcon(new javax.swing.ImageIcon("C:\\Users\\Aluno\\Downloads\\alterarIcone (1).png")); // NOI18N
        jButton1_alterar.setText("  ALTERAR");
        jButton1_alterar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        jButton1_alterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1_alterarActionPerformed(evt);
            }
        });
        jPanel3.add(jButton1_alterar, new org.netbeans.lib.awtextra.AbsoluteConstraints(1070, 280, 169, -1));

        jLabel22_FotoFisica.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        jPanel3.add(jLabel22_FotoFisica, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 200, 220, 190));

        jLabel25.setFont(new java.awt.Font("Serif", 3, 36)); // NOI18N
        jLabel25.setText("FOTO");
        jPanel3.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 150, -1, -1));

        jTextField8_IDFisica.setFont(new java.awt.Font("Arial Black", 3, 14)); // NOI18N
        jPanel3.add(jTextField8_IDFisica, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 120, 70, 40));

        jLabel28.setFont(new java.awt.Font("Serif", 3, 30)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(255, 255, 255));
        jLabel28.setText("ID");
        jPanel3.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 120, -1, 40));

        jLabel4.setIcon(new javax.swing.ImageIcon("C:\\Users\\Aluno\\Downloads\\FADETELA.jpg")); // NOI18N
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1620, 850));

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 1620, Short.MAX_VALUE)
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 850, Short.MAX_VALUE)
        );

        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton4_voltar2.setFont(new java.awt.Font("Serif", 3, 24)); // NOI18N
        jButton4_voltar2.setForeground(new java.awt.Color(51, 0, 153));
        jButton4_voltar2.setIcon(new javax.swing.ImageIcon("C:\\Users\\Aluno\\Downloads\\voltar (1).png")); // NOI18N
        jButton4_voltar2.setText(" VOLTAR");
        jButton4_voltar2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        jButton4_voltar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4_voltar2ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton4_voltar2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1060, 610, 169, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon("C:\\Users\\Aluno\\Downloads\\arrrrr.png")); // NOI18N
        jPanel4.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 190, 130));

        jLabel11.setFont(new java.awt.Font("Serif", 3, 36)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("CADASTRO PESSOA JURÍDICA");
        jPanel4.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 40, 530, 40));

        jLabel19.setFont(new java.awt.Font("Serif", 3, 30)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("ENDEREÇO");
        jPanel4.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 370, 170, 40));

        jLabel20.setFont(new java.awt.Font("Serif", 3, 30)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("EMAIL");
        jPanel4.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 320, 100, 40));

        jLabel21.setFont(new java.awt.Font("Serif", 3, 30)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setText("TELEFONE");
        jPanel4.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 270, 170, 40));

        jLabel23.setFont(new java.awt.Font("Serif", 3, 30)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(255, 255, 255));
        jLabel23.setText("CNPJ");
        jPanel4.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 220, 80, 40));

        jLabel24.setFont(new java.awt.Font("Serif", 3, 30)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(255, 255, 255));
        jLabel24.setText("ID");
        jPanel4.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 120, -1, 40));

        jLabel27.setFont(new java.awt.Font("Serif", 3, 30)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(255, 255, 255));
        jLabel27.setText("NOME");
        jPanel4.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 170, 100, 40));

        jTextField8_enderecoJuridica.setFont(new java.awt.Font("Arial Black", 3, 14)); // NOI18N
        jPanel4.add(jTextField8_enderecoJuridica, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 370, 430, 40));

        jTextField9_emailJuri.setFont(new java.awt.Font("Arial Black", 3, 14)); // NOI18N
        jPanel4.add(jTextField9_emailJuri, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 320, 300, 40));

        jTextField10_telefoneJuri.setFont(new java.awt.Font("Arial Black", 3, 14)); // NOI18N
        jPanel4.add(jTextField10_telefoneJuri, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 270, 270, 40));

        jTextField11_cnpj.setFont(new java.awt.Font("Arial Black", 3, 14)); // NOI18N
        jPanel4.add(jTextField11_cnpj, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 220, 270, 40));

        jTextField12_nomeJuridica.setFont(new java.awt.Font("Arial Black", 3, 14)); // NOI18N
        jPanel4.add(jTextField12_nomeJuridica, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 170, 490, 40));

        jLabel22_FotoFisica1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        jPanel4.add(jLabel22_FotoFisica1, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 200, 220, 190));

        jLabel26.setFont(new java.awt.Font("Serif", 3, 36)); // NOI18N
        jLabel26.setText("FOTO");
        jPanel4.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 150, -1, -1));

        jButton1_alterar1.setFont(new java.awt.Font("Serif", 3, 24)); // NOI18N
        jButton1_alterar1.setForeground(new java.awt.Color(51, 0, 153));
        jButton1_alterar1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Aluno\\Downloads\\alterarIcone (1).png")); // NOI18N
        jButton1_alterar1.setText("  ALTERAR");
        jButton1_alterar1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        jButton1_alterar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1_alterar1ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton1_alterar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1070, 280, 169, -1));

        jButton2_incluir1.setFont(new java.awt.Font("Serif", 3, 24)); // NOI18N
        jButton2_incluir1.setForeground(new java.awt.Color(51, 0, 153));
        jButton2_incluir1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Aluno\\Downloads\\incluirIcone (1).png")); // NOI18N
        jButton2_incluir1.setText("  INCLUIR");
        jButton2_incluir1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        jButton2_incluir1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2_incluir1ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton2_incluir1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1070, 240, 169, -1));

        jButton3_buscar1.setFont(new java.awt.Font("Serif", 3, 24)); // NOI18N
        jButton3_buscar1.setForeground(new java.awt.Color(51, 0, 153));
        jButton3_buscar1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Aluno\\Downloads\\lupa4.0 (1).png")); // NOI18N
        jButton3_buscar1.setText("  BUSCAR");
        jButton3_buscar1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        jButton3_buscar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3_buscar1ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton3_buscar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1070, 200, 169, -1));

        jTextField8_idJuridica.setFont(new java.awt.Font("Arial Black", 3, 14)); // NOI18N
        jPanel4.add(jTextField8_idJuridica, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 120, 70, 40));

        jLabel6.setIcon(new javax.swing.ImageIcon("C:\\Users\\Aluno\\Downloads\\FADETELA.jpg")); // NOI18N
        jPanel4.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1410, 780));

        javax.swing.GroupLayout jFrame2Layout = new javax.swing.GroupLayout(jFrame2.getContentPane());
        jFrame2.getContentPane().setLayout(jFrame2Layout);
        jFrame2Layout.setHorizontalGroup(
            jFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jFrame2Layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 1409, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jFrame2Layout.setVerticalGroup(
            jFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jFrame2Layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 780, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("cliente");

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\Aluno\\Downloads\\arrrrr.png")); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 190, 130));

        jLabel3.setFont(new java.awt.Font("Serif", 3, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("CADASTRO DE CLIENTES");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 30, 440, 40));

        jButton4_voltar.setFont(new java.awt.Font("Serif", 3, 24)); // NOI18N
        jButton4_voltar.setForeground(new java.awt.Color(51, 0, 153));
        jButton4_voltar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/MoreSupra/visao/icons/voltar (1).png"))); // NOI18N
        jButton4_voltar.setText(" VOLTAR");
        jButton4_voltar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        jButton4_voltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4_voltarActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4_voltar, new org.netbeans.lib.awtextra.AbsoluteConstraints(1110, 630, 169, -1));

        jButton1_pessoaFisica.setFont(new java.awt.Font("Serif", 3, 48)); // NOI18N
        jButton1_pessoaFisica.setForeground(new java.awt.Color(51, 0, 153));
        jButton1_pessoaFisica.setText("Pessoa Física");
        jButton1_pessoaFisica.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        jButton1_pessoaFisica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1_pessoaFisicaActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1_pessoaFisica, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 240, 340, 80));

        jButton2_pessoaJuridica.setFont(new java.awt.Font("Serif", 3, 48)); // NOI18N
        jButton2_pessoaJuridica.setForeground(new java.awt.Color(51, 0, 153));
        jButton2_pessoaJuridica.setText("Pessoa Jurídica");
        jButton2_pessoaJuridica.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        jButton2_pessoaJuridica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2_pessoaJuridicaActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2_pessoaJuridica, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 340, 340, 80));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/MoreSupra/visao/icons/gif 3.gif"))); // NOI18N
        jLabel9.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 180, 480, 220));

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/MoreSupra/visao/icons/gif 4.gif"))); // NOI18N
        jLabel12.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 410, 480, 210));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/MoreSupra/visao/icons/FADETELA.jpg"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1460, 710));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton4_voltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4_voltarActionPerformed
        // TODO add your handling code here:
        TelaPrincipal principal = new TelaPrincipal();
        principal.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton4_voltarActionPerformed

    private void jButton1_pessoaFisicaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1_pessoaFisicaActionPerformed
        // TODO add your handling code here:
        this.dispose();
        jFrame1.setVisible(true);
        jFrame1.setExtendedState(MAXIMIZED_BOTH);
    }//GEN-LAST:event_jButton1_pessoaFisicaActionPerformed

    private void jButton4_voltar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4_voltar1ActionPerformed
        // TODO add your handling code here:
        TelaCliente cliente = new TelaCliente();
        cliente.setVisible(true);
        jFrame1.dispose();
    }//GEN-LAST:event_jButton4_voltar1ActionPerformed

    private void jButton4_voltar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4_voltar2ActionPerformed
        // TODO add your handling code here:
        TelaCliente cliente = new TelaCliente();
        cliente.setVisible(true);
        jFrame2.dispose();
    }//GEN-LAST:event_jButton4_voltar2ActionPerformed

    private void jButton2_pessoaJuridicaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2_pessoaJuridicaActionPerformed
        // TODO add your handling code here:
        this.dispose();
        jFrame2.setVisible(true);
        jFrame2.setExtendedState(MAXIMIZED_BOTH);
    }//GEN-LAST:event_jButton2_pessoaJuridicaActionPerformed

    private void jButton3_buscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3_buscarActionPerformed
        // TODO add your handling code here:  
        try {
            JFileChooser fc = new JFileChooser("./src/com/MoreSupra/imagensClientes");
            File buscar = new File(".src/com/MoreSupra/imagensClientes");
            fc.setCurrentDirectory(buscar);
            fc.setFileSelectionMode(JFileChooser.FILES_ONLY);
            fc.showOpenDialog(this);
            File arquivo = fc.getSelectedFile();
            String nomeDoArquivo = arquivo.getPath();
            jLabel22_FotoFisica.setText(nomeDoArquivo);
            ImageIcon iconLogo = new ImageIcon(nomeDoArquivo);
            iconLogo.setImage(iconLogo.getImage().getScaledInstance(
                    jLabel22_FotoFisica.getWidth(), jLabel22_FotoFisica.getHeight(), 1));
            jLabel22_FotoFisica.setIcon(iconLogo);
        } catch (Exception erro) {
            JOptionPane.showMessageDialog(this, erro);
        }
    }//GEN-LAST:event_jButton3_buscarActionPerformed

    private void jButton2_incluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2_incluirActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jButton2_incluirActionPerformed

    private void jButton1_alterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1_alterarActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jButton1_alterarActionPerformed

    private void jButton1_alterar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1_alterar1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1_alterar1ActionPerformed

    private void jButton2_incluir1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2_incluir1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2_incluir1ActionPerformed

    private void jButton3_buscar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3_buscar1ActionPerformed
        // TODO add your handling code here:
        try {
            JFileChooser fc = new JFileChooser("./src/com/MoreSupra/imagensClientes");
            File buscar = new File(".src/com/MoreSupra/imagensClientes");
            fc.setCurrentDirectory(buscar);
            fc.setFileSelectionMode(JFileChooser.FILES_ONLY);
            fc.showOpenDialog(this);
            File arquivo = fc.getSelectedFile();
            String nomeDoArquivo = arquivo.getPath();
            jLabel22_FotoFisica1.setText(nomeDoArquivo);
            ImageIcon iconLogo = new ImageIcon(nomeDoArquivo);
            iconLogo.setImage(iconLogo.getImage().getScaledInstance(
                    jLabel22_FotoFisica1.getWidth(), jLabel22_FotoFisica1.getHeight(), 1));
            jLabel22_FotoFisica1.setIcon(iconLogo);
        } catch (Exception erro) {
            JOptionPane.showMessageDialog(this, erro);
        }
    }//GEN-LAST:event_jButton3_buscar1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaCliente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1_alterar;
    private javax.swing.JButton jButton1_alterar1;
    private javax.swing.JButton jButton1_pessoaFisica;
    private javax.swing.JButton jButton2_incluir;
    private javax.swing.JButton jButton2_incluir1;
    private javax.swing.JButton jButton2_pessoaJuridica;
    private javax.swing.JButton jButton3_buscar;
    private javax.swing.JButton jButton3_buscar1;
    private javax.swing.JButton jButton4_voltar;
    private javax.swing.JButton jButton4_voltar1;
    private javax.swing.JButton jButton4_voltar2;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JFrame jFrame2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22_FotoFisica;
    private javax.swing.JLabel jLabel22_FotoFisica1;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JTextField jTextField10_telefoneJuri;
    private javax.swing.JTextField jTextField11_cnpj;
    private javax.swing.JTextField jTextField12_nomeJuridica;
    private javax.swing.JTextField jTextField1_identidade;
    private javax.swing.JTextField jTextField2_nomeFisica;
    private javax.swing.JTextField jTextField3_enderecoFisica;
    private javax.swing.JTextField jTextField4_cpf;
    private javax.swing.JTextField jTextField5_telefoneFisica;
    private javax.swing.JTextField jTextField6_emailFIsica;
    private javax.swing.JTextField jTextField8_IDFisica;
    private javax.swing.JTextField jTextField8_enderecoJuridica;
    private javax.swing.JTextField jTextField8_idJuridica;
    private javax.swing.JTextField jTextField9_emailJuri;
    // End of variables declaration//GEN-END:variables
}
