/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.MoreSupra.visao;

import java.io.File;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author Aluno
 */
public class telaPessoaJuridica extends javax.swing.JFrame {

    /**
     * Creates new form telaPessoaJuridica
     */
    public telaPessoaJuridica() {
        initComponents();
        setExtendedState(MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        jButton4_voltar2 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jTextField8_enderecoJuridica = new javax.swing.JTextField();
        jTextField9_emailJuri = new javax.swing.JTextField();
        jTextField10_telefoneJuri = new javax.swing.JTextField();
        jTextField11_cnpj = new javax.swing.JTextField();
        jTextField12_nomeJuridica = new javax.swing.JTextField();
        jLabel22_FotoFisica1 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jButton1_alterar1 = new javax.swing.JButton();
        jButton2_incluir1 = new javax.swing.JButton();
        jButton3_buscar1 = new javax.swing.JButton();
        jTextField8_idJuridica = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton4_voltar2.setFont(new java.awt.Font("Serif", 3, 24)); // NOI18N
        jButton4_voltar2.setForeground(new java.awt.Color(51, 0, 153));
        jButton4_voltar2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/MoreSupra/visao/icons/voltar (1).png"))); // NOI18N
        jButton4_voltar2.setText(" VOLTAR");
        jButton4_voltar2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        jButton4_voltar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4_voltar2ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton4_voltar2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1060, 610, 169, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/MoreSupra/visao/icons/arrrrr.png"))); // NOI18N
        jPanel4.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 190, 130));

        jLabel11.setFont(new java.awt.Font("Serif", 3, 36)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("CADASTRO PESSOA JURÍDICA");
        jPanel4.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 40, 530, 40));

        jLabel19.setFont(new java.awt.Font("Serif", 3, 30)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("ENDEREÇO");
        jPanel4.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 370, 170, 40));

        jLabel20.setFont(new java.awt.Font("Serif", 3, 30)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("EMAIL");
        jPanel4.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 320, 100, 40));

        jLabel21.setFont(new java.awt.Font("Serif", 3, 30)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setText("TELEFONE");
        jPanel4.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 270, 170, 40));

        jLabel23.setFont(new java.awt.Font("Serif", 3, 30)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(255, 255, 255));
        jLabel23.setText("CNPJ");
        jPanel4.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 220, 80, 40));

        jLabel24.setFont(new java.awt.Font("Serif", 3, 30)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(255, 255, 255));
        jLabel24.setText("ID");
        jPanel4.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 120, -1, 40));

        jLabel27.setFont(new java.awt.Font("Serif", 3, 30)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(255, 255, 255));
        jLabel27.setText("NOME");
        jPanel4.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 170, 100, 40));

        jTextField8_enderecoJuridica.setFont(new java.awt.Font("Arial Black", 3, 14)); // NOI18N
        jPanel4.add(jTextField8_enderecoJuridica, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 370, 430, 40));

        jTextField9_emailJuri.setFont(new java.awt.Font("Arial Black", 3, 14)); // NOI18N
        jPanel4.add(jTextField9_emailJuri, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 320, 300, 40));

        jTextField10_telefoneJuri.setFont(new java.awt.Font("Arial Black", 3, 14)); // NOI18N
        jPanel4.add(jTextField10_telefoneJuri, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 270, 270, 40));

        jTextField11_cnpj.setFont(new java.awt.Font("Arial Black", 3, 14)); // NOI18N
        jPanel4.add(jTextField11_cnpj, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 220, 270, 40));

        jTextField12_nomeJuridica.setFont(new java.awt.Font("Arial Black", 3, 14)); // NOI18N
        jPanel4.add(jTextField12_nomeJuridica, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 170, 490, 40));

        jLabel22_FotoFisica1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        jPanel4.add(jLabel22_FotoFisica1, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 200, 220, 190));

        jLabel26.setFont(new java.awt.Font("Serif", 3, 36)); // NOI18N
        jLabel26.setText("FOTO");
        jPanel4.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 150, -1, -1));

        jButton1_alterar1.setFont(new java.awt.Font("Serif", 3, 24)); // NOI18N
        jButton1_alterar1.setForeground(new java.awt.Color(51, 0, 153));
        jButton1_alterar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/MoreSupra/visao/icons/alterarIcone.png"))); // NOI18N
        jButton1_alterar1.setText("  ALTERAR");
        jButton1_alterar1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        jButton1_alterar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1_alterar1ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton1_alterar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1070, 280, 169, -1));

        jButton2_incluir1.setFont(new java.awt.Font("Serif", 3, 24)); // NOI18N
        jButton2_incluir1.setForeground(new java.awt.Color(51, 0, 153));
        jButton2_incluir1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/MoreSupra/visao/icons/incluirIcone.png"))); // NOI18N
        jButton2_incluir1.setText("  INCLUIR");
        jButton2_incluir1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        jButton2_incluir1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2_incluir1ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton2_incluir1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1070, 240, 169, -1));

        jButton3_buscar1.setFont(new java.awt.Font("Serif", 3, 24)); // NOI18N
        jButton3_buscar1.setForeground(new java.awt.Color(51, 0, 153));
        jButton3_buscar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/MoreSupra/visao/icons/lupa4.0.png"))); // NOI18N
        jButton3_buscar1.setText("  BUSCAR");
        jButton3_buscar1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        jButton3_buscar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3_buscar1ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton3_buscar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1070, 200, 169, -1));

        jTextField8_idJuridica.setFont(new java.awt.Font("Arial Black", 3, 14)); // NOI18N
        jPanel4.add(jTextField8_idJuridica, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 120, 70, 40));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/MoreSupra/visao/icons/FADETELA.jpg"))); // NOI18N
        jPanel4.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1410, 780));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 1409, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 780, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton4_voltar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4_voltar2ActionPerformed
        // TODO add your handling code here:
        TelaPrincipal princ = new TelaPrincipal();
        princ.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton4_voltar2ActionPerformed

    private void jButton1_alterar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1_alterar1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1_alterar1ActionPerformed

    private void jButton2_incluir1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2_incluir1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2_incluir1ActionPerformed

    private void jButton3_buscar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3_buscar1ActionPerformed
        // TODO add your handling code here:
        try {
            JFileChooser fc = new JFileChooser("./src/com/MoreSupra/imagensClientes");
            File buscar = new File(".src/com/MoreSupra/imagensClientes");
            fc.setCurrentDirectory(buscar);
            fc.setFileSelectionMode(JFileChooser.FILES_ONLY);
            fc.showOpenDialog(this);
            File arquivo = fc.getSelectedFile();
            String nomeDoArquivo = arquivo.getPath();
            jLabel22_FotoFisica1.setText(nomeDoArquivo);
            ImageIcon iconLogo = new ImageIcon(nomeDoArquivo);
            iconLogo.setImage(iconLogo.getImage().getScaledInstance(
                jLabel22_FotoFisica1.getWidth(), jLabel22_FotoFisica1.getHeight(), 1));
        jLabel22_FotoFisica1.setIcon(iconLogo);
        } catch (Exception erro) {
            JOptionPane.showMessageDialog(this, erro);
        }
    }//GEN-LAST:event_jButton3_buscar1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(telaPessoaJuridica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(telaPessoaJuridica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(telaPessoaJuridica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(telaPessoaJuridica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new telaPessoaJuridica().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1_alterar1;
    private javax.swing.JButton jButton2_incluir1;
    private javax.swing.JButton jButton3_buscar1;
    private javax.swing.JButton jButton4_voltar2;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22_FotoFisica1;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JTextField jTextField10_telefoneJuri;
    private javax.swing.JTextField jTextField11_cnpj;
    private javax.swing.JTextField jTextField12_nomeJuridica;
    private javax.swing.JTextField jTextField8_enderecoJuridica;
    private javax.swing.JTextField jTextField8_idJuridica;
    private javax.swing.JTextField jTextField9_emailJuri;
    // End of variables declaration//GEN-END:variables
}
